### ISSUE TITLE
docker and duplicity multivol_snapshot

### ISSUE THREAD

**Issue by finevine** [blacklabelops/volumerize#103]
Hi,

I'm facing a problem to understand `multivol_snapshot` of dupliciy.

Trying to restore manually a db from tar.gz files, I cannot untar them because they are on multivol_snapshot.

I have 2 docker-compose using volumerize: one for preprod (rc) and one for production:

  ```yml
  rcbackup:
    # https://github.com/blacklabelops/volumerize/tree/master/backends/AmazonS3
    # https://github.com/blacklabelops/volumerize/issues/97
      image: blacklabelops/volumerize:1.6
      container_name: RcBackup
      env_file:
        - ../../.env
      restart: always
      depends_on:
        - rcdb
        - rcweb
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock  
        - /etc/timezone:/etc/timezone:ro          
        - volumerizerccache:/volumerize-cache
        - '../../db_backup:/source/db_backup:ro'
        - '../../media:/source/media:ro'
      environment:         
        - VOLUMERIZE_SOURCE=/source
        - VOLUMERIZE_CACHE=/volumerize-cache
        - VOLUMERIZE_TARGET=s3://s3.eu-west-3.amazonaws.com/${VOLUMERIZE_USER}
        - AWS_ACCESS_KEY_ID=${VOLUMERIZE_USER_ACCESS_KEY}
        - AWS_SECRET_ACCESS_KEY=${VOLUMERIZE_USER_SECRET_KEY}
        - TZ="Europe/Paris"
        - VOLUMERIZE_JOBBER_TIME=0 35 3 * * *
        # - VOLUMERIZE_JOBBER_TIME=0 1/15 * * * *
        - VOLUMERIZE_FULL_IF_OLDER_THAN=7D
        - JOB_NAME2=RemoveOldBackups
        - JOB_COMMAND2=/etc/volumerize/remove-older-than 7D --force
        - JOB_TIME2=0 40 3 * * *
      networks:
        - intern
      labels:
        - traefik.enable=false
  volumes:
    rcpgdb:
    volumerizerccache:
    rcredis-data:
```

```yml
  prodbackup:
  # https://github.com/blacklabelops/volumerize/tree/master/backends/AmazonS3
  # https://github.com/blacklabelops/volumerize/issues/97
    image: blacklabelops/volumerize:1.6
    container_name: ProdBackup
    env_file:
      - ../../.env
    restart: always
    depends_on:
      - proddb
      - prodweb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - /etc/timezone:/etc/timezone:ro          
      - volumerize-cache:/volumerize-cache
      - '../../db_backup:/source/db_backup:ro'
      - '../../media:/source/media:ro'
    environment:         
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_CACHE=/volumerize-cache
      - VOLUMERIZE_TARGET=s3://s3.eu-west-3.amazonaws.com/${VOLUMERIZE_USER}
      - AWS_ACCESS_KEY_ID=${VOLUMERIZE_USER_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${VOLUMERIZE_USER_SECRET_KEY}
      - TZ="Europe/Paris"
      - VOLUMERIZE_JOBBER_TIME=0 35 3 * * *
      - VOLUMERIZE_FULL_IF_OLDER_THAN=7D
      - JOB_NAME2=RemoveOldBackups
      - JOB_COMMAND2=/etc/volumerize/remove-older-than 365D --force
      - JOB_TIME2=0 40 3 * * *
    networks:
      - intern
    labels:
      - traefik.enable=false
volumes:
  prodpgdb:
  volumerize-cache:
  prodredis-data:
```

First, my volumes were named the same but since I've read that they must not be shared, I've changed the one for preprod to `volumerizerccache`

But now on the preprod, when I run `docker exec RcBackup backup` I'm also facing a multivol_snapshot.
I cannot understand why.

Any help? 🙏 🙏 
Thank you!
