### ISSUE TITLE
Restore with overwriting files

### ISSUE THREAD

**Issue by maksymsereda** [blacklabelops/volumerize#66]
My goal is to make restore with overwriting files? I mean I made backup, change file inside container and restore. But file is not overwriting, just if I delete file it will be restored. I use volumerize with docker-compose with such config.

```
  backups:
    container_name: volumerize
    image: myvolumerize
    restart: unless-stopped
    environment:
        - TZ=Europe/Warsaw
        - VOLUMERIZE_SOURCE=/source
        - VOLUMERIZE_TARGET=file:///backups
        - VOLUMERIZE_JOBBER_TIME=0 40 12 * * *
        - VOLUMERIZE_CONTAINERS=backend frontend postgres redis solr
        - DOCKER_API_VERSION=1.39
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ~/data/backup-cache:/volumerize-cache
        ...
        - env:/source/src/.env
        - _gunicorn_access:/source/src/._gunicorn_access.txt
        - gunicorn_log:/source/src/gunicorn_log.txt
```
Checked and if I'm backuping one file it is not possible (maybe I mistake), but if it will be a folder it is overwriting a file after changing

**Comment by blacklabelops** [comment]
Use the internal restore skript: https://github.com/blacklabelops/volumerize#container-scripts

Example:

~~~~
$ docker exec volumerize restore
~~~~

Or the simulation without overwriting:

~~~~
$ docker exec volumerize restore --dry-run
~~~~

**Comment by maksymsereda** [comment]
> Use the internal restore skript: https://github.com/blacklabelops/volumerize#container-scripts
> 
> Example:
> 
> ```
> $ docker exec volumerize restore
> ```
> Or the simulation without overwriting:
> 
> ```
> $ docker exec volumerize restore --dry-run
> ```

I want to overwrite but this command is not overwriting my file 
`$ docker exec volumerize restore`
I want to restore this file in my docker-compose.yml. 
```
backups:
    container_name: volumerize
    image: myvolumerize
    restart: unless-stopped
    environment:
        - TZ=Europe/Warsaw
        - VOLUMERIZE_SOURCE=/source
        - VOLUMERIZE_TARGET=file:///backups
        - VOLUMERIZE_JOBBER_TIME=0 40 12 * * *
        - VOLUMERIZE_CONTAINERS=backend frontend postgres redis solr
        - DOCKER_API_VERSION=1.39
    volumes:
        ...
        - celery_log:/source/celery_smtp.log
        ...
```
Do i need to add any ro/rw ?

**Comment by blacklabelops** [comment]
I think the problem is the definition of the volumes.

Docker expects directories not folders. You should check your backups. Are the  listed files are even in the backups?

You should use directories and then define includes and excludes: https://unix.stackexchange.com/questions/117761/how-to-include-exclude-directories-in-duplicity

**Comment by maksymsereda** [comment]
> Are the listed files are even in the backups?

Please tell me how to check this?
As i understand volumerize can backup directories but not files? 

```
  backend:
    image: backend
    volumes:
      - ~/data/media-data:/src/media
   solr:
    image: solr
    volumes:
      - ~/data/solr-data:/opt/solr/server/solr/mycores
  ...
  backups:
    image: myvolumerize
    environment:
        - VOLUMERIZE_SOURCE=/source
        - VOLUMERIZE_TARGET=file:///backups
        - VOLUMERIZE_CONTAINERS=backend frontend postgres redis solr
        - DOCKER_API_VERSION=1.39
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ~/data/backup-cache:/volumerize-cache
        - ~/data/media-data:/source/src/media
        - ~/data/psql-data:/source/var/lib/postgresql/data
        - ~/data/redis-data:/source/data
        - ~/data/solr-data:/source/opt/solr/server/solr/mycores
        - celery_log:/source/src/celery_smtp.log                                 #this is a file
        - gunicorn_log:/source/src/gunicorn_log.txt                             #this is a file
        - gunicorn_error:/source/src/gunicorn_error.txt                        #this is a file
        - gunicorn_access:/source/src/gunicorn_access.txt                 #this is a file
```
Could you tell me what I am doing wrong? All files above celery_smtp.log was backuped but not those files. Thanks in advance
