### ISSUE TITLE
How to add script executions in docker-compose?

### ISSUE THREAD

**Issue by jwillmer** [blacklabelops/volumerize#97]
I see that there are scripts available like `remove-older-than` but from the readme it is unclear for me how I can incorporate them into my setup. Below is my current setup and I would like to know how I can remove backups older then 1 month - I guess all scripts work the same so I can transfer the setup to the others as well.

```
  backup-to-bucket:
    image: blacklabelops/volumerize:1.6
    container_name: backup-to-bucket
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - /etc/timezone:/etc/timezone:ro          
      - volumerize-cache:/volumerize-cache
      - mysql-backups:/source/mysql:ro
    environment:         
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_CACHE=/volumerize-cache
      - VOLUMERIZE_TARGET=b2://${BACKBLAZE_BUCKET_ID}:${BACKBLAZE_BUCKET_KEY}@${BACKBLAZE_BUCKET_NAME}
      - PASSPHRASE=${VOLUMERIZE_PASSPHRASE}
      - TZ=${TZ}
      - VOLUMERIZE_JOBBER_TIME=0 30 4 * * *
      - VOLUMERIZE_FULL_IF_OLDER_THAN=7D
```
